### ISSUE TITLE
Infografía hilos Diego Cruz Cruz 

### ISSUE THREAD

**Issue by Diegocruz040708** [SistemasTecTlaxiaco/infografia-de-hilos-Diegocruz040708#2]
[Infografía de hilos de programación Diego Cruz .pdf](https://github.com/SistemasTecTlaxiaco/infografia-de-hilos-Diegocruz040708/files/15098526/Infografia.de.hilos.de.programacion.Diego.Cruz.pdf)

**Comment by Kevinosorio77** [comment]
De acuerdo ala rubrica cumple con los estándares de creatividad, diseño, composición e incluye todas las indicaciones 20/20

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
